# celery
CELERY_BROKER_URL="redis://localhost:6379"
CELERY_RESULT_BACKEND="redis://localhost:6379"

# aws
AWS_KEY=AKIAIWWIRBELNUKW65OQ
AWS_SECRET=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
AWS_BUCKET=sopview