import os

# celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL'),
#CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')

# db
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False